# Generated by Django 3.2.25 on 2024-12-05 22:56

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_Id', models.SmallIntegerField()),
                ('event_details', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('retain_length', models.SmallIntegerField()),
                ('is_done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_start_date_for_progress_calculation', models.DateTimeField(default=django.utils.timezone.now)),
                ('study_check_points', models.JSONField(default=api.models.get_default_study_check_points)),
            ],
        ),
        migrations.CreateModel(
            name='MemoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Algo', 'Algo'), ('System_Design', 'System_Design'), ('ODD', 'OOD'), ('Linux', 'Linux'), ('Network', 'Network'), ('General_IT', 'General_IT'), ('BQ', 'BQ'), ('French', 'French'), ('English', 'English'), ('Friends_Info', 'Friends_Info'), ('Math', 'Math'), ('Machine_Learning', 'Machine_Learning')], default='Algo', max_length=20)),
                ('importance_level', models.SmallIntegerField(default=1)),
                ('study_history', models.TextField(default='')),
                ('nominal_start_date_for_progress_calculation', models.DateTimeField(default=django.utils.timezone.now)),
                ('in_half_year_repetition', models.BooleanField(default=False)),
                ('record_details', models.TextField()),
                ('record_neighbor', models.CharField(default='N/A', max_length=100)),
                ('is_activate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memo_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
