# Generated by Django 3.2.25 on 2024-11-30 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_learningprogress_memorecord_onetimeevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorecord',
            name='Learning_Progress_Id',
        ),
        migrations.RemoveField(
            model_name='memorecord',
            name='id',
        ),
        migrations.AddField(
            model_name='memorecord',
            name='Check_Points',
            field=models.TextField(default=' Day_1: false\n                    Day_1_repeat: false\n                    Day_2: false\n                    Day_4: false\n                    Day_8: false\n                    Day_15: false\n                    Day_30: false\n                    Day_60: false\n                    Day_90: false\n                    Day_120: false\n                    Day_180: false\n                    Day_300: false\n                    Day_480: false\n                    Day_640: false\n                    Day_End: false\n                '),
        ),
        migrations.AddField(
            model_name='memorecord',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memo_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memorecord',
            name='in_half_year_repetition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorecord',
            name='nominal_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='memorecord',
            name='record_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='LearningProgress',
        ),
    ]
