# Generated by Django 3.2.25 on 2024-12-10 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_memorecord_onetimeevent_studyhistory_studyplan_subjecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttype',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_type', to='auth.user'),
            preserve_default=False,
        ),
    ]
