# Generated by Django 3.2.25 on 2024-12-05 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_memorecord_onetimeevent_studyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorecord',
            name='study_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_model', to='api.studyplan'),
        ),
    ]
