# Generated by Django 3.2.25 on 2024-12-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subjecttype_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subjecttype',
            name='name',
        ),
        migrations.AddField(
            model_name='subjecttype',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='category',
            field=models.CharField(default='Default Category', max_length=20),
        ),
    ]
