# Generated by Django 3.2.25 on 2024-12-02 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_check_points_memorecord_memo_plan_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorecord',
            old_name='memo_plan_progress',
            new_name='Study_Check_Points',
        ),
    ]
