# Generated by Django 3.2.25 on 2024-12-11 16:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20241210_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_scope', models.JSONField(default=api.models.get_default_study_scope)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
