# Generated by Django 3.2.25 on 2024-12-05 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studyhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorecord',
            name='study_history',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='study_history_model', to='api.studyhistory'),
        ),
    ]
