# Generated by Django 3.2.25 on 2024-12-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_memorecord_study_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyhistory',
            name='record_details_change_history',
            field=models.TextField(default=''),
        ),
    ]
