# Generated by Django 3.2.25 on 2024-12-02 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_memo_plan_progress_memorecord_study_check_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memorecord',
            name='importance_Level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='memorecord',
            name='recordNeighbor',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
