# Generated by Django 3.2.25 on 2024-12-11 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_studyscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorecord',
            name='study_scope_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='study_scope_model', to='api.studyscope'),
        ),
    ]
