# Generated by Django 3.2.25 on 2024-12-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_memorecord_study_scope_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorecord',
            name='study_scope_id',
        ),
    ]
