# Generated by Django 3.2.25 on 2024-12-05 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_studyhistory_record_details_change_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyhistory',
            old_name='today_study_count',
            new_name='study_days_count',
        ),
    ]
