# Generated by Django 3.2.25 on 2024-12-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20241202_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
