# Generated by Django 3.2.25 on 2024-12-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20241202_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorecord',
            name='id',
        ),
        migrations.AddField(
            model_name='memorecord',
            name='record_Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
