# Generated by Django 3.2.25 on 2024-12-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_today_study_count_studyhistory_study_days_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorecord',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
