# Generated by Django 3.2.25 on 2024-12-11 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_memorecord_study_scope_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyscope',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='study_scope', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
