# Generated by Django 3.2.25 on 2024-12-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_memorecord_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
