# Generated by Django 3.2.25 on 2024-12-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_memorecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorecord',
            name='Study_Check_Points',
            field=models.JSONField(default={'Day_1': 'false', 'Day_120': 'false', 'Day_15': 'false', 'Day_180': 'false', 'Day_2': 'false', 'Day_30': 'false', 'Day_300': 'false', 'Day_4': 'false', 'Day_480': 'false', 'Day_60': 'false', 'Day_640': 'false', 'Day_8': 'false', 'Day_90': 'false', 'Day_End': 'false'}),
        ),
    ]
