# Generated by Django 3.2.25 on 2024-12-02 22:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_memorecord_study_check_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorecord',
            name='Study_Check_Points',
            field=models.JSONField(default=api.models.get_default_study_check_points),
        ),
    ]
