# Generated by Django 3.2.25 on 2024-12-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20241211_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorecord',
            name='question',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='memorecord',
            name='record_details',
            field=models.TextField(default='N/A'),
        ),
    ]
