# Generated by Django 3.2.25 on 2024-12-14 16:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20241211_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimeevent',
            name='event_Id',
        ),
        migrations.RemoveField(
            model_name='onetimeevent',
            name='retain_length',
        ),
        migrations.AddField(
            model_name='onetimeevent',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='one_time_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onetimeevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 14, 16, 48, 37, 271119, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onetimeevent',
            name='event_history',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='onetimeevent',
            name='event_name',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onetimeevent',
            name='is_very_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onetimeevent',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='onetimeevent',
            name='event_details',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='onetimeevent',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
