# Generated by Django 3.2.25 on 2024-12-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_onetimeevent_event_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimeEvent',
        ),
    ]
