# Generated by Django 3.2.25 on 2024-12-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_onetimeevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimeevent',
            old_name='is_very_important',
            new_name='is_high_importance',
        ),
    ]
