# Generated by Django 3.2.25 on 2024-12-15 02:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_is_very_important_onetimeevent_is_high_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeevent',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 2, 14, 6, 381766, tzinfo=utc)),
        ),
    ]
