# Generated by Django 3.2.25 on 2024-12-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_onetimeevent_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeevent',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
