# Generated by Django 3.2.25 on 2024-12-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_onetimeevent_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeevent',
            name='event_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='onetimeevent',
            name='event_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='onetimeevent',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
