# Generated by Django 3.2.25 on 2025-03-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_blog_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='memorecord',
            name='subject_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='category',
            field=models.CharField(default='SDE_Interview', max_length=20),
        ),
    ]
