# Generated by Django 4.2.20 on 2025-04-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_memorecord_current_learning_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorecord',
            name='current_Learning_Session',
        ),
        migrations.AddField(
            model_name='memorecord',
            name='current_learning_session',
            field=models.BooleanField(default=False),
        ),
    ]
